"""
Export Utilities
Generate PDF and DOCX files from analysis results
"""

import io
from datetime import datetime
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def generate_pdf(analysis_data: dict) -> bytes:
    """
    Generate PDF from analysis results

    Args:
        analysis_data: Analysis results dictionary

    Returns:
        PDF file as bytes
    """
    buffer = io.BytesIO()

    # Create PDF document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72
    )

    # Container for the 'Flowable' objects
    elements = []

    # Define styles
    styles = getSampleStyleSheet()

    # Title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#0ea5e9'),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )

    # Heading style
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#0ea5e9'),
        spaceAfter=12,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )

    # Normal style
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=12,
        alignment=TA_JUSTIFY,
        fontName='Helvetica'
    )

    # Add title
    title = Paragraph("Contract Analysis Report", title_style)
    elements.append(title)
    elements.append(Spacer(1, 0.2*inch))

    # Add metadata
    metadata = [
        ['Contract:', analysis_data.get('contract_filename', 'N/A')],
        ['Analysis Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')],
        ['Status:', analysis_data.get('status', 'N/A').upper()],
    ]

    metadata_table = Table(metadata, colWidths=[2*inch, 4*inch])
    metadata_table.setStyle(TableStyle([
        ('FONT', (0, 0), (-1, -1), 'Helvetica', 10),
        ('FONT', (0, 0), (0, -1), 'Helvetica-Bold', 10),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#374151')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))

    elements.append(metadata_table)
    elements.append(Spacer(1, 0.3*inch))

    # Add analysis sections
    results = analysis_data.get('results', {})

    if results:
        for section_name, section_content in results.items():
            # Section heading
            heading = Paragraph(section_name.replace('_', ' ').title(), heading_style)
            elements.append(heading)

            # Section content
            if isinstance(section_content, dict):
                content_text = format_dict_for_pdf(section_content)
            elif isinstance(section_content, list):
                content_text = format_list_for_pdf(section_content)
            else:
                content_text = str(section_content)

            content = Paragraph(content_text, normal_style)
            elements.append(content)
            elements.append(Spacer(1, 0.2*inch))
    else:
        no_results = Paragraph("No analysis results available.", normal_style)
        elements.append(no_results)

    # Add footer
    elements.append(PageBreak())
    footer_text = "Generated by Legally AI - Contract Analysis Platform"
    footer = Paragraph(footer_text, ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.grey,
        alignment=TA_CENTER
    ))
    elements.append(Spacer(1, 8*inch))
    elements.append(footer)

    # Build PDF
    doc.build(elements)

    # Get PDF bytes
    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes


def generate_docx(analysis_data: dict) -> bytes:
    """
    Generate DOCX from analysis results

    Args:
        analysis_data: Analysis results dictionary

    Returns:
        DOCX file as bytes
    """
    doc = Document()

    # Set document margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    # Add title
    title = doc.add_heading('Contract Analysis Report', level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.runs[0]
    title_run.font.color.rgb = RGBColor(14, 165, 233)  # #0ea5e9
    title_run.font.size = Pt(24)

    doc.add_paragraph()

    # Add metadata
    metadata_table = doc.add_table(rows=3, cols=2)
    metadata_table.style = 'Light Grid Accent 1'

    metadata_cells = [
        ('Contract:', analysis_data.get('contract_filename', 'N/A')),
        ('Analysis Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')),
        ('Status:', analysis_data.get('status', 'N/A').upper()),
    ]

    for i, (label, value) in enumerate(metadata_cells):
        row = metadata_table.rows[i]
        row.cells[0].text = label
        row.cells[1].text = value

        # Make labels bold
        label_run = row.cells[0].paragraphs[0].runs[0]
        label_run.font.bold = True

    doc.add_paragraph()

    # Add analysis sections
    results = analysis_data.get('results', {})

    if results:
        for section_name, section_content in results.items():
            # Section heading
            heading = doc.add_heading(section_name.replace('_', ' ').title(), level=1)
            heading_run = heading.runs[0]
            heading_run.font.color.rgb = RGBColor(14, 165, 233)

            # Section content
            if isinstance(section_content, dict):
                for key, value in section_content.items():
                    p = doc.add_paragraph()
                    p.add_run(f"{key.replace('_', ' ').title()}: ").bold = True
                    p.add_run(str(value))
            elif isinstance(section_content, list):
                for item in section_content:
                    doc.add_paragraph(str(item), style='List Bullet')
            else:
                doc.add_paragraph(str(section_content))

            doc.add_paragraph()
    else:
        doc.add_paragraph("No analysis results available.")

    # Add footer
    doc.add_page_break()
    footer_para = doc.add_paragraph("Generated by Legally AI - Contract Analysis Platform")
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_para.runs[0]
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(128, 128, 128)

    # Save to bytes
    buffer = io.BytesIO()
    doc.save(buffer)
    docx_bytes = buffer.getvalue()
    buffer.close()

    return docx_bytes


def format_dict_for_pdf(data: dict) -> str:
    """Format dictionary for PDF paragraph"""
    lines = []
    for key, value in data.items():
        key_formatted = key.replace('_', ' ').title()
        lines.append(f"<b>{key_formatted}:</b> {value}")
    return "<br/>".join(lines)


def format_list_for_pdf(data: list) -> str:
    """Format list for PDF paragraph"""
    lines = []
    for i, item in enumerate(data, 1):
        lines.append(f"{i}. {item}")
    return "<br/>".join(lines)
