/**
 * Export Lawyer Handoff Pack (AF-003)
 * Comprehensive PDF report for legal counsel
 */

import jsPDF from 'jspdf'

interface LawyerPackOptions {
  title: string
  content: any
  metadata: {
    contractName: string
    analysisDate: string
    confidenceScore?: number
  }
  analysisData?: any
}

export async function exportLawyerPackToPDF(options: LawyerPackOptions): Promise<void> {
  const { title, content, metadata, analysisData } = options
  const doc = new jsPDF()

  let yPosition = 20
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentWidth = pageWidth - 2 * margin

  // Helper function to add new page if needed
  const checkPageBreak = (neededSpace: number = 20) => {
    if (yPosition + neededSpace > pageHeight - 20) {
      doc.addPage()
      yPosition = 20
      return true
    }
    return false
  }

  // Helper to add text with word wrap
  const addText = (text: string, fontSize: number = 11, isBold: boolean = false) => {
    doc.setFontSize(fontSize)
    doc.setFont('helvetica', isBold ? 'bold' : 'normal')

    const lines = doc.splitTextToSize(text, contentWidth)
    lines.forEach((line: string) => {
      checkPageBreak()
      doc.text(line, margin, yPosition)
      yPosition += fontSize * 0.5
    })
    yPosition += 3
  }

  // ============================================
  // COVER PAGE
  // ============================================

  // Logo placeholder (centered)
  doc.setFillColor(79, 70, 229) // primary-600
  doc.rect(pageWidth / 2 - 15, yPosition, 30, 30, 'F')
  yPosition += 40

  // Title
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('LAWYER HANDOFF PACK', pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 15

  // Subtitle
  doc.setFontSize(16)
  doc.setFont('helvetica', 'normal')
  doc.text('Contract Analysis Report', pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 30

  // Metadata box
  doc.setFillColor(249, 250, 251) // gray-50
  doc.rect(margin, yPosition, contentWidth, 50, 'F')
  doc.setDrawColor(229, 231, 235) // gray-200
  doc.rect(margin, yPosition, contentWidth, 50, 'S')

  yPosition += 10
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('Contract:', margin + 5, yPosition)
  doc.setFont('helvetica', 'normal')
  doc.text(metadata.contractName, margin + 35, yPosition)

  yPosition += 10
  doc.setFont('helvetica', 'bold')
  doc.text('Analysis Date:', margin + 5, yPosition)
  doc.setFont('helvetica', 'normal')
  doc.text(metadata.analysisDate, margin + 35, yPosition)

  yPosition += 10
  doc.setFont('helvetica', 'bold')
  doc.text('Generated By:', margin + 5, yPosition)
  doc.setFont('helvetica', 'normal')
  doc.text('Legally AI - Contract Analysis Platform', margin + 35, yPosition)

  yPosition += 10
  if (metadata.confidenceScore !== undefined) {
    doc.setFont('helvetica', 'bold')
    doc.text('Confidence:', margin + 5, yPosition)
    doc.setFont('helvetica', 'normal')
    const confidenceText = `${Math.round(metadata.confidenceScore * 100)}%`
    doc.text(confidenceText, margin + 35, yPosition)
  }

  yPosition += 30

  // Important Notice
  doc.setFillColor(254, 243, 199) // yellow-100
  doc.rect(margin, yPosition, contentWidth, 40, 'F')
  doc.setDrawColor(251, 191, 36) // yellow-400
  doc.rect(margin, yPosition, contentWidth, 40, 'S')

  yPosition += 10
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('⚠️  IMPORTANT NOTICE', margin + 5, yPosition)
  yPosition += 7
  doc.setFont('helvetica', 'normal')
  const disclaimerLines = doc.splitTextToSize(
    'This analysis was generated by AI and should be reviewed by qualified legal counsel. It does not constitute legal advice. Please verify all key terms and dates with the original contract.',
    contentWidth - 10
  )
  disclaimerLines.forEach((line: string) => {
    doc.text(line, margin + 5, yPosition)
    yPosition += 5
  })

  // New page for content
  doc.addPage()
  yPosition = 20

  // ============================================
  // EXECUTIVE SUMMARY
  // ============================================

  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('EXECUTIVE SUMMARY', margin, yPosition)
  yPosition += 10

  doc.setLineWidth(0.5)
  doc.line(margin, yPosition, pageWidth - margin, yPosition)
  yPosition += 10

  // About the contract
  if (content.about?.description) {
    addText('Overview:', 12, true)
    addText(content.about.description)
    yPosition += 5
  }

  // Screening result
  if (analysisData?.screening_result) {
    addText('Initial Assessment:', 12, true)
    const screeningMap: Record<string, string> = {
      no_major_issues: '✓ No major issues identified',
      recommended_to_address: '⚠️  Issues recommended to address before signing',
      high_risk: '🚨 High-risk terms identified - legal review strongly recommended',
      preliminary_review: 'ℹ️  Preliminary review - verification recommended',
    }
    addText(screeningMap[analysisData.screening_result] || analysisData.screening_result)
    yPosition += 5
  }

  // ============================================
  // KEY TERMS SUMMARY
  // ============================================

  checkPageBreak(30)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('KEY TERMS SUMMARY', margin, yPosition)
  yPosition += 10
  doc.setLineWidth(0.5)
  doc.line(margin, yPosition, pageWidth - margin, yPosition)
  yPosition += 10

  // Payment Terms
  if (content.payment_terms?.content) {
    addText('Payment Terms:', 12, true)
    const terms = content.payment_terms.content
    if (typeof terms === 'object' && !Array.isArray(terms)) {
      Object.entries(terms).forEach(([key, value]) => {
        if (value) {
          addText(`• ${key.replace(/_/g, ' ')}: ${value}`, 10)
        }
      })
    }
    yPosition += 5
  }

  // ============================================
  // OBLIGATIONS
  // ============================================

  if (content.obligations?.content && content.obligations.content.length > 0) {
    checkPageBreak(30)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('YOUR OBLIGATIONS', margin, yPosition)
    yPosition += 10
    doc.setLineWidth(0.5)
    doc.line(margin, yPosition, pageWidth - margin, yPosition)
    yPosition += 10

    content.obligations.content.forEach((obl: any, index: number) => {
      checkPageBreak(25)
      addText(`${index + 1}. ${obl.action}`, 11, true)
      if (obl.time_window) {
        addText(`   Timeline: ${obl.time_window}`, 10)
      }
      if (obl.consequence) {
        addText(`   If not done: ${obl.consequence}`, 10)
      }
      yPosition += 3
    })
    yPosition += 5
  }

  // ============================================
  // RISKS & CONCERNS
  // ============================================

  if (content.risks?.content && content.risks.content.length > 0) {
    checkPageBreak(30)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('RISKS & CONCERNS', margin, yPosition)
    yPosition += 10
    doc.setLineWidth(0.5)
    doc.line(margin, yPosition, pageWidth - margin, yPosition)
    yPosition += 10

    content.risks.content.forEach((risk: any, index: number) => {
      checkPageBreak(30)

      // Risk level badge
      const levelColors: Record<string, [number, number, number]> = {
        high: [220, 38, 38], // red-600
        medium: [217, 119, 6], // yellow-600
        low: [22, 163, 74], // green-600
      }
      const color = levelColors[risk.level] || [107, 114, 128] // gray-500
      doc.setFillColor(...color)
      doc.rect(margin, yPosition - 3, 15, 5, 'F')
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(8)
      doc.text(risk.level.toUpperCase(), margin + 2, yPosition)
      doc.setTextColor(0, 0, 0)

      yPosition += 7
      addText(`${index + 1}. ${risk.description}`, 11, true)
      if (risk.recommendation) {
        addText(`   → Recommendation: ${risk.recommendation}`, 10)
      }
      yPosition += 3
    })
    yPosition += 5
  }

  // ============================================
  // SUGGESTED CHANGES
  // ============================================

  if (content.suggestions?.content && content.suggestions.content.length > 0) {
    checkPageBreak(30)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('SUGGESTED CHANGES TO REQUEST', margin, yPosition)
    yPosition += 10
    doc.setLineWidth(0.5)
    doc.line(margin, yPosition, pageWidth - margin, yPosition)
    yPosition += 10

    addText('Consider requesting these changes during negotiation:', 10)
    yPosition += 3

    content.suggestions.content.forEach((suggestion: any, index: number) => {
      checkPageBreak(15)
      const text = typeof suggestion === 'string' ? suggestion : suggestion.text || suggestion.description
      addText(`${index + 1}. ${text}`, 10)
    })
    yPosition += 5
  }

  // ============================================
  // MITIGATIONS
  // ============================================

  if (content.mitigations?.content && content.mitigations.content.length > 0) {
    checkPageBreak(30)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('RISK MITIGATION STEPS', margin, yPosition)
    yPosition += 10
    doc.setLineWidth(0.5)
    doc.line(margin, yPosition, pageWidth - margin, yPosition)
    yPosition += 10

    addText('If signing as-is, take these steps to reduce risks:', 10)
    yPosition += 3

    content.mitigations.content.forEach((mitigation: any, index: number) => {
      checkPageBreak(15)
      const text = typeof mitigation === 'string' ? mitigation : mitigation.text || mitigation.description
      addText(`${index + 1}. ${text}`, 10)
    })
    yPosition += 5
  }

  // ============================================
  // KEY DATES & DEADLINES
  // ============================================

  if (content.calendar?.content && content.calendar.content.length > 0) {
    checkPageBreak(30)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('KEY DATES & DEADLINES', margin, yPosition)
    yPosition += 10
    doc.setLineWidth(0.5)
    doc.line(margin, yPosition, pageWidth - margin, yPosition)
    yPosition += 10

    content.calendar.content.forEach((item: any) => {
      checkPageBreak(15)
      const date = item.date_or_formula || item.date || 'TBD'
      const event = item.event || item.description || 'No description'

      doc.setFont('helvetica', 'bold')
      doc.text(`📅 ${date}`, margin, yPosition)
      yPosition += 6
      doc.setFont('helvetica', 'normal')
      const eventLines = doc.splitTextToSize(event, contentWidth - 10)
      eventLines.forEach((line: string) => {
        doc.text(line, margin + 5, yPosition)
        yPosition += 5
      })
      yPosition += 3
    })
    yPosition += 5
  }

  // ============================================
  // QUESTIONS FOR COUNSEL
  // ============================================

  checkPageBreak(30)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('QUESTIONS FOR LEGAL COUNSEL', margin, yPosition)
  yPosition += 10
  doc.setLineWidth(0.5)
  doc.line(margin, yPosition, pageWidth - margin, yPosition)
  yPosition += 10

  const questions = [
    'Are there any jurisdictional issues with this contract that we should be aware of?',
    'Do the payment terms align with industry standards for this type of agreement?',
    'Are the liability limitations reasonable and enforceable?',
    'Should we request any additional protections or clauses?',
    'Are there any regulatory compliance issues we need to address?',
    'What are the risks if we proceed with signing as-is?',
  ]

  questions.forEach((question, index) => {
    checkPageBreak(15)
    addText(`${index + 1}. ${question}`, 10)
  })

  yPosition += 10

  // ============================================
  // FOOTER ON EVERY PAGE
  // ============================================

  const totalPages = doc.internal.pages.length - 1 // Subtract 1 for the internal page counter
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(156, 163, 175) // gray-400
    doc.text(
      `Generated by Legally AI | ${metadata.analysisDate} | Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    )
    doc.setTextColor(0, 0, 0)
  }

  // Save the PDF
  const filename = `lawyer-pack-${metadata.contractName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`
  doc.save(filename)
}
